{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3fd3a4ab-76cf-4781-a7f2-cfe2fb8d1afb",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "Note: Here Exception class refers to the base class for all the exceptions.\n",
    "\n",
    "When creating a custom exception in Python, it is important to inherit from the built-in Exception class or one of its subclasses. This is because Exception provides a set of attributes and methods that are necessary for properly handling and reporting errors in a program.\n",
    "Here are a few reasons why we should use the Exception class as the base class for custom exceptions:\n",
    "Inheritance: The Exception class provides a well-defined hierarchy for handling exceptions. By inheriting from Exception, our custom exception becomes a part of this hierarchy and can be caught and handled along with other built-in exceptions.\n",
    "Error Reporting: The Exception class provides attributes like args and message that can be used to provide more detailed information about the error that occurred. By using these attributes in our custom exception, we can provide better error reporting for our users.\n",
    "Standardization: By using the Exception class as the base class for our custom exception, we are following a well-established convention in Python. This makes our code more understandable and maintainable for other developers who might be working on the same project.\n",
    "Overall, using the Exception class as the base class for custom exceptions ensures that our exceptions are compatible with the rest of the Python exception hierarchy and provides the necessary attributes and methods for handling and reporting errors.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f497dd06-f8d1-4b0f-936f-0c9abce94e6b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "TypeError\n",
      "   FloatOperation\n",
      "   MultipartConversionError\n",
      "StopAsyncIteration\n",
      "StopIteration\n",
      "ImportError\n",
      "   ModuleNotFoundError\n",
      "   ZipImportError\n",
      "OSError\n",
      "   ConnectionError\n",
      "     BrokenPipeError\n",
      "     ConnectionAbortedError\n",
      "     ConnectionRefusedError\n",
      "     ConnectionResetError\n",
      "   BlockingIOError\n",
      "   ChildProcessError\n",
      "   FileExistsError\n",
      "   FileNotFoundError\n",
      "   IsADirectoryError\n",
      "   NotADirectoryError\n",
      "   InterruptedError\n",
      "     InterruptedSystemCall\n",
      "   PermissionError\n",
      "   ProcessLookupError\n",
      "   TimeoutError\n",
      "   UnsupportedOperation\n",
      "   itimer_error\n",
      "   herror\n",
      "   gaierror\n",
      "   SSLError\n",
      "     SSLCertVerificationError\n",
      "     SSLZeroReturnError\n",
      "     SSLWantWriteError\n",
      "     SSLWantReadError\n",
      "     SSLSyscallError\n",
      "     SSLEOFError\n",
      "   Error\n",
      "     SameFileError\n",
      "   SpecialFileError\n",
      "   ExecError\n",
      "   ReadError\n",
      "   URLError\n",
      "     HTTPError\n",
      "     ContentTooShortError\n",
      "   BadGzipFile\n",
      "EOFError\n",
      "   IncompleteReadError\n",
      "RuntimeError\n",
      "   RecursionError\n",
      "   NotImplementedError\n",
      "     ZMQVersionError\n",
      "     StdinNotImplementedError\n",
      "   _DeadlockError\n",
      "   BrokenBarrierError\n",
      "   BrokenExecutor\n",
      "     BrokenThreadPool\n",
      "   SendfileNotAvailableError\n",
      "   ExtractionError\n",
      "   VariableError\n",
      "NameError\n",
      "   UnboundLocalError\n",
      "AttributeError\n",
      "   FrozenInstanceError\n",
      "SyntaxError\n",
      "   IndentationError\n",
      "     TabError\n",
      "LookupError\n",
      "   IndexError\n",
      "   KeyError\n",
      "     NoSuchKernel\n",
      "     UnknownBackend\n",
      "   CodecRegistryError\n",
      "ValueError\n",
      "   UnicodeError\n",
      "     UnicodeEncodeError\n",
      "     UnicodeDecodeError\n",
      "     UnicodeTranslateError\n",
      "   UnsupportedOperation\n",
      "   JSONDecodeError\n",
      "   SSLCertVerificationError\n",
      "   Error\n",
      "   UnsupportedDigestmodError\n",
      "   IllegalMonthError\n",
      "   IllegalWeekdayError\n",
      "   ParserError\n",
      "   ClassNotFound\n",
      "   ClipboardEmpty\n",
      "   MessageDefect\n",
      "     NoBoundaryInMultipartDefect\n",
      "     StartBoundaryNotFoundDefect\n",
      "     CloseBoundaryNotFoundDefect\n",
      "     FirstHeaderLineIsContinuationDefect\n",
      "     MisplacedEnvelopeHeaderDefect\n",
      "     MissingHeaderBodySeparatorDefect\n",
      "     MultipartInvariantViolationDefect\n",
      "     InvalidMultipartContentTransferEncodingDefect\n",
      "     UndecodableBytesDefect\n",
      "     InvalidBase64PaddingDefect\n",
      "     InvalidBase64CharactersDefect\n",
      "     InvalidBase64LengthDefect\n",
      "     HeaderDefect\n",
      "   MacroToEdit\n",
      "   InvalidFileException\n",
      "   UnequalIterablesError\n",
      "   InvalidVersion\n",
      "   _InvalidELFFileHeader\n",
      "   InvalidWheelFilename\n",
      "   InvalidSdistFilename\n",
      "   InvalidSpecifier\n",
      "   InvalidMarker\n",
      "   UndefinedComparison\n",
      "   UndefinedEnvironmentName\n",
      "   InvalidRequirement\n",
      "     RequirementParseError\n",
      "   InvalidVersion\n",
      "AssertionError\n",
      "ArithmeticError\n",
      "   FloatingPointError\n",
      "   OverflowError\n",
      "   ZeroDivisionError\n",
      "     DivisionByZero\n",
      "     DivisionUndefined\n",
      "   DecimalException\n",
      "     Clamped\n",
      "     Rounded\n",
      "     Inexact\n",
      "     Subnormal\n",
      "     DivisionByZero\n",
      "     FloatOperation\n",
      "     InvalidOperation\n",
      "SystemError\n",
      "   CodecRegistryError\n",
      "ReferenceError\n",
      "MemoryError\n",
      "BufferError\n",
      "Warning\n",
      "   UserWarning\n",
      "     GetPassWarning\n",
      "     FormatterWarning\n",
      "   EncodingWarning\n",
      "   DeprecationWarning\n",
      "     ProvisionalWarning\n",
      "   PendingDeprecationWarning\n",
      "   SyntaxWarning\n",
      "   RuntimeWarning\n",
      "     ProactorSelectorThreadWarning\n",
      "     UnknownTimezoneWarning\n",
      "     PEP440Warning\n",
      "   FutureWarning\n",
      "     ProvisionalCompleterWarning\n",
      "   ImportWarning\n",
      "   UnicodeWarning\n",
      "   BytesWarning\n",
      "   ResourceWarning\n",
      "   DeprecatedTzFormatWarning\n",
      "   PkgResourcesDeprecationWarning\n",
      "_OptionError\n",
      "_Error\n",
      "error\n",
      "Verbose\n",
      "Error\n",
      "SubprocessError\n",
      "   CalledProcessError\n",
      "   TimeoutExpired\n",
      "TokenError\n",
      "StopTokenizing\n",
      "ClassFoundException\n",
      "EndOfBlock\n",
      "TraitError\n",
      "Error\n",
      "Error\n",
      "   CancelledError\n",
      "   TimeoutError\n",
      "   InvalidStateError\n",
      "_GiveupOnSendfile\n",
      "error\n",
      "Incomplete\n",
      "TimeoutError\n",
      "InvalidStateError\n",
      "LimitOverrunError\n",
      "QueueEmpty\n",
      "QueueFull\n",
      "Empty\n",
      "Full\n",
      "ArgumentError\n",
      "ZMQBaseError\n",
      "   ZMQError\n",
      "     ContextTerminated\n",
      "     Again\n",
      "     InterruptedSystemCall\n",
      "   ZMQBindError\n",
      "   NotDone\n",
      "PickleError\n",
      "   PicklingError\n",
      "   UnpicklingError\n",
      "_Stop\n",
      "ArgumentError\n",
      "ArgumentTypeError\n",
      "ConfigError\n",
      "   ConfigLoaderError\n",
      "     ArgumentError\n",
      "   ConfigFileNotFound\n",
      "ConfigurableError\n",
      "   MultipleInstanceError\n",
      "ApplicationError\n",
      "error\n",
      "TimeoutError\n",
      "error\n",
      "ReturnValueIgnoredError\n",
      "KeyReuseError\n",
      "UnknownKeyError\n",
      "LeakedCallbackError\n",
      "BadYieldError\n",
      "ReturnValueIgnoredError\n",
      "Return\n",
      "InvalidPortNumber\n",
      "error\n",
      "LZMAError\n",
      "RegistryError\n",
      "_GiveupOnFastCopy\n",
      "Error\n",
      "   NoSectionError\n",
      "   DuplicateSectionError\n",
      "   DuplicateOptionError\n",
      "   NoOptionError\n",
      "   InterpolationError\n",
      "     InterpolationMissingOptionError\n",
      "     InterpolationSyntaxError\n",
      "     InterpolationDepthError\n",
      "   ParsingError\n",
      "     MissingSectionHeaderError\n",
      "NoIPAddresses\n",
      "BadZipFile\n",
      "LargeZipFile\n",
      "BadEntryPoint\n",
      "NoSuchEntryPoint\n",
      "DuplicateKernelError\n",
      "ErrorDuringImport\n",
      "NotOneValueFound\n",
      "CannotEval\n",
      "OptionError\n",
      "BdbQuit\n",
      "Restart\n",
      "ExceptionPexpect\n",
      "   EOF\n",
      "   TIMEOUT\n",
      "PtyProcessError\n",
      "FindCmdError\n",
      "HomeDirError\n",
      "ProfileDirError\n",
      "IPythonCoreError\n",
      "   TryNext\n",
      "   UsageError\n",
      "   StdinNotImplementedError\n",
      "InputRejected\n",
      "GetoptError\n",
      "ErrorToken\n",
      "PrefilterError\n",
      "AliasError\n",
      "   InvalidAliasError\n",
      "Error\n",
      "   InterfaceError\n",
      "   DatabaseError\n",
      "     InternalError\n",
      "     OperationalError\n",
      "     ProgrammingError\n",
      "     IntegrityError\n",
      "     DataError\n",
      "     NotSupportedError\n",
      "Warning\n",
      "SpaceInInput\n",
      "DOMException\n",
      "   IndexSizeErr\n",
      "   DomstringSizeErr\n",
      "   HierarchyRequestErr\n",
      "   WrongDocumentErr\n",
      "   InvalidCharacterErr\n",
      "   NoDataAllowedErr\n",
      "   NoModificationAllowedErr\n",
      "   NotFoundErr\n",
      "   NotSupportedErr\n",
      "   InuseAttributeErr\n",
      "   InvalidStateErr\n",
      "   SyntaxErr\n",
      "   InvalidModificationErr\n",
      "   NamespaceErr\n",
      "   InvalidAccessErr\n",
      "   ValidationErr\n",
      "ValidationError\n",
      "EditReadOnlyBuffer\n",
      "_Retry\n",
      "InvalidLayoutError\n",
      "HeightIsUnknownError\n",
      "ParserSyntaxError\n",
      "InternalParseError\n",
      "_PositionUpdatingFinished\n",
      "SimpleGetItemNotFound\n",
      "UncaughtAttributeError\n",
      "HasNoContext\n",
      "ParamIssue\n",
      "_JediError\n",
      "   InternalError\n",
      "   WrongVersion\n",
      "   RefactoringError\n",
      "OnErrorLeaf\n",
      "InvalidPythonEnvironment\n",
      "MessageError\n",
      "   MessageParseError\n",
      "     HeaderParseError\n",
      "     BoundaryError\n",
      "   MultipartConversionError\n",
      "   CharsetError\n",
      "Error\n",
      "HTTPException\n",
      "   NotConnected\n",
      "   InvalidURL\n",
      "   UnknownProtocol\n",
      "   UnknownTransferEncoding\n",
      "   UnimplementedFileMode\n",
      "   IncompleteRead\n",
      "   ImproperConnectionState\n",
      "     CannotSendRequest\n",
      "     CannotSendHeader\n",
      "     ResponseNotReady\n",
      "   BadStatusLine\n",
      "     RemoteDisconnected\n",
      "   LineTooLong\n",
      "InteractivelyDefined\n",
      "KillEmbedded\n",
      "Error\n",
      "   NoSuchProcess\n",
      "     ZombieProcess\n",
      "   AccessDenied\n",
      "   TimeoutExpired\n",
      "_Ipv6UnsupportedError\n",
      "QueueEmpty\n",
      "QueueFull\n",
      "DebuggerInitializationError\n",
      "ExpatError\n",
      "Error\n",
      "   ProtocolError\n",
      "   ResponseError\n",
      "   Fault\n",
      "ParseBaseException\n",
      "   ParseException\n",
      "   ParseFatalException\n",
      "     ParseSyntaxException\n",
      "RecursiveGrammarException\n",
      "ResolutionError\n",
      "   VersionConflict\n",
      "     ContextualVersionConflict\n",
      "   DistributionNotFound\n",
      "   UnknownExtra\n",
      "_Error\n",
      "UnableToResolveVariableException\n",
      "InvalidTypeInArgsException\n"
     ]
    }
   ],
   "source": [
    "#Q2.Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "# iterate through the Exception hierarchy and print each class\n",
    "for cls in Exception.__subclasses__():\n",
    "    print(cls.__name__)\n",
    "    for subcls in cls.__subclasses__():\n",
    "        print(\"  \", subcls.__name__)\n",
    "        # handle cases where subclasses have their own sub-classes\n",
    "        for subsubcls in subcls.__subclasses__():\n",
    "            print(\"    \", subsubcls.__name__)\n",
    "\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "f3d526ae-0281-48b6-846c-cdfeb56739de",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 8\u001b[0m\n\u001b[1;32m      6\u001b[0m a \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m5\u001b[39m\n\u001b[1;32m      7\u001b[0m b \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[0;32m----> 8\u001b[0m c \u001b[38;5;241m=\u001b[39m \u001b[43ma\u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[43mb\u001b[49m   \u001b[38;5;66;03m# ZeroDivisionError: division by zero\u001b[39;00m\n\u001b[1;32m     10\u001b[0m \u001b[38;5;66;03m#2.OverflowError: This error occurs when a number is too large to be represented in memory. For example:\u001b[39;00m\n\u001b[1;32m     11\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mmath\u001b[39;00m\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "#Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "#The ArithmeticError class is a built-in exception class in Python that serves as a base class for all errors related to arithmetic operations. It is a subclass of the Exception class, which is the base class for all built-in exceptions in Python.\n",
    "#Some of the errors defined in the ArithmeticError class include:\n",
    "#1.ZeroDivisionError: This error occurs when an attempt is made to divide a number by zero. For example:\n",
    "a = 5\n",
    "b = 0\n",
    "c = a/b   # ZeroDivisionError: division by zero\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "3ad359aa-db0f-4b11-a8d5-a2450c3b119c",
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "invalid literal for int() with base 10: 'hello'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[6], line 4\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#2.OverflowError: This error occurs when a number is too large to be represented in memory. For example:\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \n\u001b[1;32m      3\u001b[0m \u001b[38;5;66;03m#3.ValueError: This error occurs when an argument to a function or method is of the correct type but has an invalid value.\u001b[39;00m\n\u001b[0;32m----> 4\u001b[0m a \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mint\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mhello\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m   \u001b[38;5;66;03m# ValueError: invalid literal for int() with base 10: 'hello'\u001b[39;00m\n\u001b[1;32m      6\u001b[0m \u001b[38;5;66;03m#4.FloatingPointError: This error occurs when a floating-point calculation cannot be performed correctly.\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;66;03m#5.AssertionError: This error occurs when an assertion fails\u001b[39;00m\n",
      "\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: 'hello'"
     ]
    }
   ],
   "source": [
    "#2.OverflowError: This error occurs when a number is too large to be represented in memory. For example:\n",
    "\n",
    "#3.ValueError: This error occurs when an argument to a function or method is of the correct type but has an invalid value.\n",
    "a = int('hello')   # ValueError: invalid literal for int() with base 10: 'hello'\n",
    "\n",
    "#4.FloatingPointError: This error occurs when a floating-point calculation cannot be performed correctly.\n",
    "#5.AssertionError: This error occurs when an assertion fails"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f2430815-92b2-4c90-abde-b8d2c6f4db8b",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'pear'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[9], line 10\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \n\u001b[1;32m      3\u001b[0m \u001b[38;5;66;03m#The LookupError class is a built-in exception class in Python that serves as the base class for all errors related to accessing an index or key that is out of range or does not exist. It is a subclass of the Exception class, which is the base class for all built-in exceptions in Python.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m      6\u001b[0m \n\u001b[1;32m      7\u001b[0m \u001b[38;5;66;03m#KeyError: This error occurs when a dictionary key is not found in the dictionary. For example:\u001b[39;00m\n\u001b[1;32m      9\u001b[0m my_dict \u001b[38;5;241m=\u001b[39m {\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mapple\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m1\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mbanana\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m2\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124morange\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m3\u001b[39m}\n\u001b[0;32m---> 10\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mmy_dict\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mpear\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m)   \u001b[38;5;66;03m# KeyError: 'pear'\u001b[39;00m\n",
      "\u001b[0;31mKeyError\u001b[0m: 'pear'"
     ]
    }
   ],
   "source": [
    "#Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "#The LookupError class is a built-in exception class in Python that serves as the base class for all errors related to accessing an index or key that is out of range or does not exist. It is a subclass of the Exception class, which is the base class for all built-in exceptions in Python.\n",
    "#The LookupError class is used to handle situations where a program tries to access an element in a collection (like a list, tuple, or dictionary) using an index or key that is out of range or does not exist. This can happen if the index/key is larger than the length of the collection or if the index/key does not correspond to any element in the collection.\n",
    "#Two common errors that are subclasses of the LookupError class are KeyError and IndexError.\n",
    "\n",
    "#KeyError: This error occurs when a dictionary key is not found in the dictionary. For example:\n",
    "\n",
    "my_dict = {'apple': 1, 'banana': 2, 'orange': 3}\n",
    "print(my_dict['pear'])   # KeyError: 'pear'\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "5d119d8e-8631-435f-9b89-d72a3ebf91ce",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[8], line 4\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#IndexError: This error occurs when an index is out of range for a list or tuple. For example:\u001b[39;00m\n\u001b[1;32m      3\u001b[0m my_list \u001b[38;5;241m=\u001b[39m [\u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m2\u001b[39m, \u001b[38;5;241m3\u001b[39m]\n\u001b[0;32m----> 4\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mmy_list\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m3\u001b[39;49m\u001b[43m]\u001b[49m)    \u001b[38;5;66;03m# IndexError: list index out of range\u001b[39;00m\n\u001b[1;32m      6\u001b[0m \u001b[38;5;66;03m#In both cases, the LookupError class is used because the program is trying to access an element using an index or key that does not exist. By catching these errors with try and except blocks, we can handle these situations gracefully and provide a more informative error message to the user.\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;66;03m#Overall, the LookupError class is an important part of the Python exception hierarchy because it provides a common base class for all errors related to accessing elements in a collection.\u001b[39;00m\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "#IndexError: This error occurs when an index is out of range for a list or tuple. For example:\n",
    "\n",
    "my_list = [1, 2, 3]\n",
    "print(my_list[3])    # IndexError: list index out of range\n",
    "\n",
    "#In both cases, the LookupError class is used because the program is trying to access an element using an index or key that does not exist. By catching these errors with try and except blocks, we can handle these situations gracefully and provide a more informative error message to the user.\n",
    "#Overall, the LookupError class is an important part of the Python exception hierarchy because it provides a common base class for all errors related to accessing elements in a collection."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "753c96d0-d189-4739-bcc7-590bad1a9b7d",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (1378641102.py, line 3)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[10], line 3\u001b[0;36m\u001b[0m\n\u001b[0;31m    ImportError is a built-in exception class in Python that is raised when a module cannot be imported. This error typically occurs when the Python interpreter is unable to find the module specified in the import statement, or when the module is found but cannot be loaded for some reason.\u001b[0m\n\u001b[0m                     ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "ImportError is a built-in exception class in Python that is raised when a module cannot be imported. This error typically occurs when the Python interpreter is unable to find the module specified in the import statement, or when the module is found but cannot be loaded for some reason.\n",
    "For example, consider the following code:\n",
    "\n",
    "import non_existent_module   # ImportError: No module named 'non_existent_module'\n",
    "\n",
    "In this case, the ImportError is raised because there is no module named non_existent_module that can be imported.\n",
    "ModuleNotFoundError is a subclass of ImportError that was introduced in Python 3.6 to provide a more informative error message when a module cannot be found. Prior to Python 3.6, the ImportError exception was used for both cases where a module could not be found and for other types of import errors.\n",
    "For example, consider the following code:\n",
    "    \n",
    "import non_existent_module   # ModuleNotFoundError: No module named 'non_existent_module'\n",
    "\n",
    "In this case, the ModuleNotFoundError is raised instead of ImportError because the module non_existent_module could not be found.\n",
    "Overall, ImportError and ModuleNotFoundError are both important exceptions in Python that indicate that a module could not be imported for some reason. The difference between them is that ModuleNotFoundError provides a more specific error message when the module cannot be found, while ImportError is a more general error that can be raised for other types of import errors as well."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d7a9d64e-61cf-4b4e-aeef-11504d62f819",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "Only catch exceptions that you can handle: It's important to catch only the exceptions that you can handle in a meaningful way. Catching all exceptions can make it difficult to debug issues and can also hide underlying problems.\n",
    "\n",
    "Use specific exception classes: Catching specific exception classes instead of using a general catch-all statement can help to make the code more readable and also provide more specific information about the error.\n",
    "\n",
    "Handle exceptions at the appropriate level: Exceptions should be handled at the appropriate level of the code. For example, if an exception occurs in a function, it should be caught and handled within that function, rather than being propagated up to the higher level of the code.\n",
    "\n",
    "Use finally blocks for cleanup: The finally block is always executed, regardless of whether an exception is raised or not. This makes it a good place to put code that needs to be executed for cleanup purposes, such as closing files or database connections.\n",
    "\n",
    "Avoid using bare except clauses: Using a bare except clause to catch all exceptions can make it difficult to debug issues and can also hide underlying problems. It's better to catch specific exceptions or use a general catch-all clause at the appropriate level of the code.\n",
    "\n",
    "Don't suppress exceptions: Suppressing exceptions by catching them and not doing anything with them can lead to unexpected behavior and make it difficult to debug issues. Always log or handle exceptions in a meaningful way.\n",
    "\n",
    "Use try-except blocks sparingly: Using too many try-except blocks can make the code harder to read and maintain. It's better to write code that handles errors gracefully without the use of try-except blocks, where possible."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
